### PR TITLE
Fix duplicate addition of offset time on switchLatest

### PR DESCRIPTION
**Pull request by gitusp**
This fixes https://github.com/mostjs/core/issues/284.

I confirmed that the original `switchLatest` emits an error event with time `2`, which should be `1`, and removing ` + this.min` from `Segment#_dispose` resolves the issue.

To be honest, I find my way of writing test case pretty clumsy, but I could not find a  straightforward way to examine the case.
Feel free to request changes, I'll appreciate it.

Thank you.

### CODE REVIEW

**Comment by briancavalier** [comment]
Hey @gitusp, thanks for doing this!

This is very much an edge case.  That said, I agree it's probably harder than it should be to observe the time value in this particular case.

Here's a thought on a slightly simpler approach using some of the testing utilities in core/test/helpers.  I'm sorry these are as well-documented as we'd like them to be.  FakeDisposeStream is from test/helpers/FakeDisposeStream.

```js
// new imports
import FakeDisposeStream from './helper/FakeDisposeStream'
import { run } from '../src/run'

 // ...
      const inner = FakeDisposeStream.from(() => { throw new Error() }, at(1))
      const s = at(1, inner)
      const sink = {
        event () {},
        end (t) {},
        error (t, e) {
          try {
            eq(2, t)
            done()
          } catch (e) {
            done(e)
          }
        }
      }

      run(sink, ticks(2), switchLatest(s))
```

What do you think?

**Comment by gitusp** [comment]
Thank you @briancavalier! That's way simpler and cleaner.

I applied your suggestion and pushed again.
Sorry for having you write almost all the code. 🙇

**Comment by briancavalier** [comment]
> Sorry for having you write almost all the code.

Haha, no worries at all, @gitusp.  Team work!

**Comment by briancavalier** [comment]
Published in `@most/core` 1.3.5.  Thanks again!

**Pull request merged**
