### PR TITLE
add missing eslint dependencies

### PR DESCRIPTION
**Pull request by nikoskalogridis**

### CODE REVIEW

**Comment by briancavalier** [comment]
Hi @nikoskalogridis, I apologize about the confusion here.  We have [switched to using standard](https://github.com/mostjs/core/blob/master/packages/prelude/package.json#L18), and `@most/eslint-config-most` is deprecated.  So, I think the right thing to do would be for us to delete the straggling `.eslintrc` files.  I'd be happy to do that, since it was a mess I made :) but if you'd rather do it in order to keep moving, that's fine too (and I'd be very thankful!).

**Comment by nikoskalogridis** [comment]
@briancavalier sure I could remove it myself, no problem ;-)

**Comment by briancavalier** [comment]
Thank you! I’d really appreciate it.

**Comment by nikoskalogridis** [comment]
closing in favour of #226

**Pull request closed without merging**
