### PR TITLE
ADR: Add static types

### PR DESCRIPTION
**Pull request by briancavalier**
ADR for adding static types into the source.  Very interested to hear others' thoughts on pros and cons.

### CODE REVIEW

**Comment by TylorS** [comment]
Does anyone know of places in the codebase where adding types would require a large refactoring?

**Comment by briancavalier** [comment]
I'll bet there are some gunky place inside `@most/scheduler` where it might be tricky.  Otherwise, I don't think it will be too bad if we can go incrementally.  A lot of the code was written with types in mind, even though they aren't explicit.

I was thinking a good approach would be to start with `@most/disposable` and some key parts of `@most/core` like `slice`, `map`, and maybe `mergeConcurrently`.  With Flow, that should be relatively simple by incrementally adding `// @flow`.  Initially, that will only get us a little type safety, but as we add more coverage, obviously, we'll get more and more benefit.

Is it possible to do a similar incremental approach with TypeScript?  What are the mechanics of it? (incrementally renaming files to .ts?)

**Comment by TylorS** [comment]
You can slowly convert to .ts files with the right tsconfig. With noImplicitAny and allowJs set to true I believe.

With just noImplicitAny true it's also pretty easy to mass rename to .ts since JS is valid TS.

**Comment by briancavalier** [comment]
Thanks @TylorS.  I like the idea of renaming files incrementally so it's easy to tell at a glance which files have been converted and which haven't.  With Flow, we could tell by `// @flow` comments.

There's also [flow-coverage-report](https://www.npmjs.com/package/flow-coverage-report) (and just plain old `flow coverage`), as well as [type-coverage](https://www.npmjs.com/package/type-coverage) for TS.

**Comment by nikoskalogridis** [comment]
My personal opinion would be to switch to using Flow types.

Advantages:

- Keeping the current build stack (babel, rollup) intact
- Completely static type check all the files in the code base
- Gradually migrate files (without renaming all of them in .ts)
- If we decide to change this decision and revert to plain Javascript we can simply strip the Flow types from the files and be done with it
- If we decide to switch to Typescript at some time in the future that will be easier as we would already have made most of the work required. We would only need to change some incompatibilities between Flow and Typescript.

**Comment by briancavalier** [comment]
Ported to TypeScript in #296 🎉

**Pull request closed without merging**
